global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'api_gateway'
    static_configs:
      - targets: ['api_gateway:9100']

  - job_name: 'auth_service'
    static_configs:
      - targets: ['auth_service:9100']

  - job_name: 'worker_service'
    static_configs:
      - targets: ['worker_service:9100']
